import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

//Import the header and footer to be at the top and bottom of every page
import Header from "./Header/Header";
import Footer from "./Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//Set the header and footer at the top and bottom of every page
export default function RootLayout({children}: {children: React.ReactNode;}) {
  return (
    <html lang="en">
      <body>
        <header>
          <Header/>
        </header>
        <main>
          {children}
        </main>
        <Footer/>
      </body>
    </html>
  );
}
