import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

//Import the header and footer to be at the top and bottom of every page
import Header from "./Header/Header";
import Footer from "./Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
